#include<iostream>
using namespace std;
int main (){
    int a,b,c;
    cin>>a>>b>>c;
    if(a*100+b*10+c>=a*100+c*10+b){
        if(a*100+b*10+c>=b*100+c*10+a){
            if(a*100+b*10+c>=b*100+a*10+c){
                if(a*100+b*10+c>=c*100+a*10+b){
                    if(a*100+b*10+c>=c*100+b*10+a){
                        cout<<a*100+b*10+c<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
                else{
                    if(c*100+a*10+b>=c*100+b*10+a){
                        cout<<c*100+a*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
            }
            else{
                if(b*100+a*10+c>=c*100+a*10+b){
                    if(b*100+a*10+c>=c*100+b*10+a){
                        cout<<b*100+a*10+c<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
                else{
                    if(c*100+a*10+b>=c*100+b*10+a){
                        cout<<c*100+a*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
            }
        }
        else{
            if(b*100+c*10+a>=b*100+a*10+c){
                if(b*100+c*10+a>=c*100+a*10+b){
                    if(b*100+c*10+a>=c*100+b*10+a){
                        cout<<b*100+c*10+a<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
                else{
                    if(c*100+a*10+b>=c*100+b*10+a){
                        cout<<c*100+a*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
            }
            else{
                if(b*100+a*10+c>=c*100+a*10+b){
                    if(b*100+a*10+c>=c*100+b*10+a){
                        cout<<b*100+a*10+c<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
                else{
                    if(c*100+a*10+b>=c*100+b*10+a){
                        cout<<c*100+a*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
            }
        }
    }
    else{if(a*100+c*10+b>=b*100+c*10+a){
            if(a*100+c*10+b>=b*100+a*10+c){
                if(a*100+c*10+b>=c*100+a*10+b){
                    if(a*100+c*10+b>=c*100+b*10+a){
                        cout<<a*100+c*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
                else{
                    if(c*100+a*10+b>=c*100+b*10+a){
                        cout<<c*100+a*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
            }
            else{
                if(b*100+a*10+c>=c*100+a*10+b){
                    if(b*100+a*10+c>=c*100+b*10+a){
                        cout<<b*100+a*10+c<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
                else{
                    if(c*100+a*10+b>=c*100+b*10+a){
                        cout<<c*100+a*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
            }
        }
        else{
            if(b*100+c*10+a>=b*100+a*10+c){
                if(b*100+c*10+a>=c*100+a*10+b){
                    if(b*100+c*10+a>=c*100+b*10+a){
                        cout<<b*100+c*10+a<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
                else{
                    if(c*100+a*10+b>=c*100+b*10+a){
                        cout<<c*100+a*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
            }
            else{
                if(b*100+a*10+c>=c*100+a*10+b){
                    if(b*100+a*10+c>=c*100+b*10+a){
                        cout<<b*100+a*10+c<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
                else{
                    if(c*100+a*10+b>=c*100+b*10+a){
                        cout<<c*100+a*10+b<<endl;
                    }
                    else{
                        cout<<c*100+b*10+a<<endl;
                    }
                }
            }
        }
    }
    return 0;}
